### ISSUE TITLE
nema potrebe da uvodih novu promenljivu, odmah vrati vrednost 

### ISSUE THREAD

**Issue by BoskoNikolic** [z1z0v1c/learning-samples#1]
https://github.com/azizovic-endava/alex-java-zadaci/blob/681248b3ceac76367e4ab2685a5f528071829878/ParniBrojevi/src/ParniBrojevi.java#L42

**Comment by z1z0v1c** [comment]
Pokusavao sam da zatvorim skener izmedju promenjive i return, ali nije htelo. Posle sam zaboravio da ispravim. Na nekim mestima jesam, posto mi se ista metoda ponavlja vise puta.
