### ISSUE TITLE
Nije ti dobar uslov. Trazeno je ako je razlika izmedju unetog i random broja manja od 5. 

### ISSUE THREAD

**Issue by BoskoNikolic** [z1z0v1c/learning-samples#10]
https://github.com/azizovic-endava/alex-java-zadaci/blob/681248b3ceac76367e4ab2685a5f528071829878/PogodiBroj2/src/PogodiBroj.java#L35

**Comment by z1z0v1c** [comment]
Nisam obratio paznju. U originalnom zadatku je 5 ili manja.
