### ISSUE TITLE
Imena metoda i promenljivih treba da budu deskriptivna. unosBrojaStudenata je mnogo razumljivije od unostInt

### ISSUE THREAD

**Issue by BoskoNikolic** [z1z0v1c/learning-samples#4]
https://github.com/azizovic-endava/alex-java-zadaci/blob/681248b3ceac76367e4ab2685a5f528071829878/Studenti/src/Studenti.java#L37

**Comment by z1z0v1c** [comment]
Imam istu metoda za proveru unosa za int i string u svim zadacima, zbog toga sam ih tako nazvao na svim mestima. Preimenovacu ih.
